### ISSUE TITLE
Close this repository and/or add deprecation warning

### ISSUE THREAD

**Issue by ruudk** [mpclarkson/resque-bundle#16]
Please add link to the new repo.

It's very confusing to have 2 forks :)

**Comment by PhilETaylor** [comment]
There already is a massive paragraph on the deaden page 

This old repo cant be closed/deleted as some people might still have this as a composer dependency :-)

**Comment by ruudk** [comment]
Would be nice to add it to the description too

<img width="409" alt="screen shot 2016-08-09 at 13 45 42" src="https://cloud.githubusercontent.com/assets/104180/17515258/96ea51a0-5e37-11e6-8d60-cb7172ee2686.png">

**Comment by PhilETaylor** [comment]
I have no access to that - only @mpclarkson could do that.

**Comment by mpclarkson** [comment]
Done.

**Comment by ruudk** [comment]
@mpclarkson Can you also please abondon this on Packagist? And suggest the other repo?

https://packagist.org/packages/mpclarkson/resque-bundle

**Comment by ruudk** [comment]
You can do that by logging in, and click this:
<img width="251" alt="screen shot 2016-08-11 at 09 15 09" src="https://cloud.githubusercontent.com/assets/104180/17581174/1f63898a-5fa4-11e6-8b71-836df87fd444.png">

**Comment by mpclarkson** [comment]
Done, thanks @ruudk
