### ISSUE TITLE
Move bundle to its own Github organisation

### ISSUE THREAD

**Issue by pascaldevink** [mpclarkson/resque-bundle#6]
How about moving this bundle to its own Github organisation? That would:
1. make it a lot easier to ensure the future of the bundle;
2. make it easier to transfer the bundle to whoever wants to maintain it in the future;
3. make the namespace agnostic to the maintainer

I think this bundle has proven to be pretty stable code-wise, but most of the doubts about its future are about the maintenance. The previous maintainer up and left without a notice and you already said you are willing to promote this bundle, but don't have the resources to fully do so (see https://github.com/mpclarkson/resque-bundle/pull/5#issuecomment-234418771).

Therefor, I think the best thing to ensure a safe future for the bundle and its users is to transfer it to a new Github organisation, where maintainers can work on the codebase if necessary, but the codebase isn't dependant on the maintainer anymore. Anyone can step in to do maintenance, without heavy forking and other nasty workarounds.

What do you think?

**Comment by mpclarkson** [comment]
@pascaldevink, Sorry for the delayed reply. Yes, I think that is a good idea. Any Organisation name suggestions?

**Comment by pascaldevink** [comment]
`Resque` comes to mind. It's already taken and used for the original ruby resque library, but we could ask to join them.

Another suggestion might be `ResqueBundle`. Plain and simple.
Or go with something completely fictional, and choose something from the random generator (http://fantasynamegenerators.com/brand-names.php).

**Comment by PhilETaylor** [comment]
I have done the initial work on creating the new organisation and repo here:

https://github.com/resquebundle/resque/

Once @mpclarkson is made the owner/admin of this, we can start the process of moving the manifests to point to the new repo and prune this one with a moved message.

**Comment by PhilETaylor** [comment]
I have completed the namespace changes and published the new packages to packagist

see: https://packagist.org/packages/resquebundle/resque

To migrate you need to 

```
composer remove mpclarkson/resque-bundle
composer require resquebundle/resque
```

Then in your code 
- Replace all Mpclarkson\ResqueBundle with ResqueBundle\Resque
- Remove old AppKernel.php  `new Mpclarkson\ResqueBundle\ResqueBundle()`
- Ensure AppKernel.php loads `new ResqueBundle\Resque\ResqueBundle(),`

Other than that it should work, and Im using the new resquebundle/resque exclusively loaded from composer in 2 projects now.

Contributions and new organisation members welcome :) 

To be clear, Im not trying to take over this project from @mpclarkson, Im just trying to fix some bugs, and help future development :)
