### ISSUE TITLE
Composer require doesnt allow installation

### ISSUE THREAD

**Issue by PhilETaylor** [mpclarkson/resque-bundle#7]
```
composer update
    1/1:    http://packagist.org/p/provider-latest$fb1b9d9bc039a52d33c337aa06fb3d09833d0aa91137620d2c5405d4cf011fbe.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Loading composer repositories with package information
Updating dependencies (including require-dev)                
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mpclarkson/resque-bundle dev-master -> satisfiable by mpclarkson/resque-bundle[dev-master].
    - mpclarkson/resque-bundle dev-master requires chrisboulton/php-resque dev-master#df69e8980cc21652f10cd775cb6a0e8c572ffd2d -> satisfiable by chrisboulton/php-resque[dev-master] but these conflict with your requirements or minimum-stability.


```

**Comment by PhilETaylor** [comment]
Solved by placing 

```
    "chrisboulton/php-resque": "dev-master#df69e8980cc21652f10cd775cb6a0e8c572ffd2d",
    "chrisboulton/php-resque-scheduler": "dev-master#ab8bd52949cac1f815bbb97aa39f51c7b5766a86",
```

in my own composer.json, then running an update then adding your

`"mpclarkson/resque-bundle": "dev-master"`

and running composer update

I'm not sure why you are still referencing the chrisboulton repo when you state its unmaintained and the purpose of your project was to replace it?

**Comment by mpclarkson** [comment]
Hi @PhilETaylor thanks for opening these ieeus. The objective of this library is to replace the `BCCResqueBundle` not the underlying `php-resque` libraries. I've locked these to specific sha's as @ chrisboulton has not released any new stable tags in a long time and I don't want an unrestricted dependency on a a dev branch. Regards, MC

**Comment by PhilETaylor** [comment]
My bad - I was juggling being a dad and coding at the same time - never a good thing to do.

My comment about the link to "unmaintained" repo was that I mistook the link to the php-resque as a link to BCCResqueBundle :-) #brainfart

The fact remains, that without placing these references in my own composer.json and installing (composer update) those BEFORE requiring your mpclarkson/resque-bundle, I was not able to get an install to work.
